on:
  schedule:
    - cron: '53 9 */3 * *'
  push:
    branches:
      - master


jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller odpy.spec
      - run: move config/, data/, mods/, _.js, game.txt, README.md, syncData.json dist/odpy/
      - run: python update_cache.py
      - run: move adb.zip, frida-server-*.xz, aria2c.exe dist/odpy/ -ErrorAction SilentlyContinue
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: dist/odpy/
